"""add enhanced fields and new models

Revision ID: fa9430914c71
Revises: abc123
Create Date: 2025-12-11 15:49:07.404431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9430914c71'
down_revision: Union[str, Sequence[str], None] = 'abc123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False, default=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False, default='public'),
    sa.Column('data_sharing', sa.Boolean(), nullable=False, default=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_account_settings_id'), 'account_settings', ['id'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('flagged_words', sa.JSON(), nullable=True),
    sa.Column('moderator_decision', sa.Text(), nullable=False),
    sa.Column('moderated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_id'), 'moderation_logs', ['id'], unique=False)
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('tax_contributions', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('stock_price', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('is_public', sa.Boolean(), nullable=False, default=False))
    op.add_column('reviews', sa.Column('is_current_employee', sa.Boolean(), nullable=False, default=True))
    op.add_column('reviews', sa.Column('employment_end_date', sa.Date(), nullable=True))
    op.add_column('reviews', sa.Column('is_anonymous', sa.Boolean(), nullable=False, default=False))
    op.add_column('reviews', sa.Column('recommendations', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('work_location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_company_id')
    op.drop_column('users', 'current_position')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('reviews', 'work_location')
    op.drop_column('reviews', 'recommendations')
    op.drop_column('reviews', 'is_anonymous')
    op.drop_column('reviews', 'employment_end_date')
    op.drop_column('reviews', 'is_current_employee')
    op.drop_column('companies', 'is_public')
    op.drop_column('companies', 'stock_price')
    op.drop_column('companies', 'tax_contributions')
    op.drop_column('companies', 'founded_year')
    op.drop_index(op.f('ix_moderation_logs_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_account_settings_id'), table_name='account_settings')
    op.drop_table('account_settings')
    # ### end Alembic commands ###
